# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-03 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bangumi',
            fields=[
                ('race_key', models.IntegerField(primary_key=True, serialize=False, verbose_name='レースキー')),
                ('syussou_tousuu', models.IntegerField(verbose_name='出走頭数')),
                ('syoukin', models.IntegerField(verbose_name='1着賞金')),
            ],
        ),
        migrations.CreateModel(
            name='Kishu_Sabun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kisyu_code', models.IntegerField(verbose_name='騎手コード')),
                ('kisyu_mei', models.CharField(blank=True, max_length=8, verbose_name='騎手名')),
                ('kisyu_fukusyou', models.DecimalField(decimal_places=9, max_digits=10, verbose_name='騎手複勝率')),
            ],
        ),
        migrations.CreateModel(
            name='Kyousouba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_key', models.IntegerField(verbose_name='レースキー')),
                ('blad_int', models.IntegerField(verbose_name='血統登録番号')),
                ('umaban', models.IntegerField(verbose_name='馬番')),
                ('zensou_seiseki_key', models.IntegerField(verbose_name='前走競争成績キー')),
                ('zensou_race_key', models.IntegerField(verbose_name='前走レースキー')),
                ('kyakushitu', models.IntegerField(verbose_name='脚質')),
            ],
        ),
        migrations.CreateModel(
            name='Tyokuzen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_key', models.IntegerField(verbose_name='レースキー')),
                ('umaban', models.IntegerField(verbose_name='馬番')),
                ('kinryou', models.IntegerField(verbose_name='斤量')),
                ('bataijyu', models.IntegerField(verbose_name='馬体重')),
                ('taijyu_zougen', models.IntegerField(verbose_name='体重増減')),
            ],
        ),
        migrations.CreateModel(
            name='Uma_kihon',
            fields=[
                ('blad_int', models.IntegerField(primary_key=True, serialize=False, verbose_name='血統登録番号')),
                ('name', models.CharField(blank=True, max_length=54, verbose_name='馬名')),
                ('birthday', models.DateTimeField(verbose_name='生年月日')),
                ('sex', models.IntegerField(verbose_name='性別')),
            ],
        ),
        migrations.CreateModel(
            name='Zensou',
            fields=[
                ('seiseki_key', models.IntegerField(primary_key=True, serialize=False, verbose_name='競争成績キー')),
                ('zensou_kyori', models.IntegerField(verbose_name='前走距離')),
                ('zensou_tm_sa', models.IntegerField(verbose_name='前走タイム差')),
                ('zensou_3ftm_before', models.IntegerField(verbose_name='前走前3Fタイム')),
                ('zensou_3ftm_after', models.IntegerField(verbose_name='前走後3Fタイム')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tyokuzen',
            unique_together=set([('race_key', 'umaban')]),
        ),
        migrations.AlterUniqueTogether(
            name='kyousouba',
            unique_together=set([('race_key', 'umaban')]),
        ),
    ]
