# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-22 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bangumi',
            fields=[
                ('history', models.CharField(default='00000000', max_length=8, verbose_name='作成年月日')),
                ('race_key', models.IntegerField(primary_key=True, serialize=False, verbose_name='レースキー')),
                ('syussou_tousuu', models.IntegerField(verbose_name='出走頭数')),
                ('syoukin', models.IntegerField(verbose_name='1着賞金')),
            ],
        ),
        migrations.CreateModel(
            name='Chokuzen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(default='00000000', max_length=8, verbose_name='作成年月日')),
                ('race_key', models.IntegerField(verbose_name='レースキー')),
                ('umaban', models.IntegerField(verbose_name='馬番')),
                ('kishu_code', models.CharField(blank=True, max_length=5, verbose_name='騎手コード')),
                ('kinryou', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='斤量')),
                ('bataijyu', models.CharField(blank=True, max_length=3, verbose_name='馬体重')),
                ('taijyu_zougen', models.CharField(blank=True, max_length=3, verbose_name='体重増減')),
            ],
        ),
        migrations.CreateModel(
            name='Kishu_Sabun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(default='00000000', max_length=8, verbose_name='作成年月日')),
                ('kishu_code', models.IntegerField(verbose_name='騎手コード')),
                ('kishu_mei', models.CharField(blank=True, max_length=8, verbose_name='騎手名')),
                ('kishu_fukusyou', models.DecimalField(decimal_places=9, max_digits=10, verbose_name='騎手複勝率')),
            ],
        ),
        migrations.CreateModel(
            name='Kyousouba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(default='00000000', max_length=8, verbose_name='作成年月日')),
                ('race_key', models.IntegerField(verbose_name='レースキー')),
                ('umaban', models.IntegerField(verbose_name='馬番')),
                ('blad_int', models.IntegerField(verbose_name='血統登録番号')),
                ('kyakushitu', models.IntegerField(verbose_name='脚質')),
                ('zensou_seiseki_key', models.CharField(blank=True, max_length=16, verbose_name='前走競争成績キー')),
                ('zensou_race_key', models.CharField(blank=True, max_length=8, verbose_name='前走レースキー')),
            ],
        ),
        migrations.CreateModel(
            name='Kyousouba_Extend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(default='00000000', max_length=8, verbose_name='作成年月日')),
                ('race_key', models.IntegerField(verbose_name='レースキー')),
                ('umaban', models.IntegerField(verbose_name='馬番')),
                ('jra_seiseki_1chaku', models.IntegerField(verbose_name='JRA成績1着')),
                ('jra_seiseki_2chaku', models.IntegerField(verbose_name='JRA成績2着')),
                ('jra_seiseki_3chaku', models.IntegerField(verbose_name='JRA成績3着')),
                ('jra_seiseki_chakugai', models.IntegerField(verbose_name='JRA成績着外')),
            ],
        ),
        migrations.CreateModel(
            name='Uma_kihon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.CharField(default='00000000', max_length=8, verbose_name='作成年月日')),
                ('blad_int', models.IntegerField(default=0, verbose_name='血統登録番号')),
                ('name', models.CharField(blank=True, max_length=54, verbose_name='馬名')),
                ('birthday', models.DateTimeField(verbose_name='生年月日')),
                ('sex', models.IntegerField(verbose_name='性別')),
            ],
        ),
        migrations.CreateModel(
            name='Zensou',
            fields=[
                ('history', models.CharField(default='00000000', max_length=8, verbose_name='作成年月日')),
                ('seiseki_key', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='競争成績キー')),
                ('zensou_kyori', models.IntegerField(verbose_name='前走距離')),
                ('zensou_tm_sa', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='前走タイム差')),
                ('zensou_3ftm_before', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='前走前3Fタイム')),
                ('zensou_3ftm_after', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='前走後3Fタイム')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='uma_kihon',
            unique_together=set([('history', 'blad_int')]),
        ),
        migrations.AlterUniqueTogether(
            name='kyousouba_extend',
            unique_together=set([('history', 'race_key', 'umaban')]),
        ),
        migrations.AlterUniqueTogether(
            name='kyousouba',
            unique_together=set([('history', 'race_key', 'umaban')]),
        ),
        migrations.AlterUniqueTogether(
            name='kishu_sabun',
            unique_together=set([('history', 'kishu_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='chokuzen',
            unique_together=set([('history', 'race_key', 'umaban')]),
        ),
        migrations.AlterUniqueTogether(
            name='bangumi',
            unique_together=set([('history', 'race_key')]),
        ),
    ]
