# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyousouba_Extend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_key', models.IntegerField(verbose_name='レースキー')),
                ('umaban', models.IntegerField(verbose_name='馬番')),
                ('jra_seiseki_1chaku', models.IntegerField(verbose_name='JRA成績1着')),
                ('jra_seiseki_2chaku', models.IntegerField(verbose_name='JRA成績2着')),
                ('jra_seiseki_3chaku', models.IntegerField(verbose_name='JRA成績3着')),
                ('jra_seiseki_chakugai', models.IntegerField(verbose_name='JRA成績着外')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='kyousouba_extend',
            unique_together=set([('race_key', 'umaban')]),
        ),
    ]
