# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-08 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0002_auto_20170908_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyousouba',
            name='zensou_seiseki_key',
            field=models.CharField(blank=True, max_length=16, verbose_name='前走競争成績キー'),
        ),
    ]
