# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-08 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0003_auto_20170908_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyousouba',
            name='zensou_race_key',
            field=models.CharField(blank=True, max_length=8, verbose_name='前走レースキー'),
        ),
    ]
