# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-09 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0004_auto_20170908_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zensou',
            name='seiseki_key',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='競争成績キー'),
        ),
    ]
