# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-09 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0005_auto_20170909_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zensou',
            name='zensou_3ftm_after',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='前走後3Fタイム'),
        ),
        migrations.AlterField(
            model_name='zensou',
            name='zensou_3ftm_before',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='前走前3Fタイム'),
        ),
        migrations.AlterField(
            model_name='zensou',
            name='zensou_tm_sa',
            field=models.DecimalField(decimal_places=2, max_digits=3, verbose_name='前走タイム差'),
        ),
    ]
