# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-09 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0006_auto_20170909_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyokuzen',
            name='kisyu_code',
            field=models.CharField(blank=True, max_length=5, verbose_name='騎手コード'),
        ),
        migrations.AlterField(
            model_name='tyokuzen',
            name='bataijyu',
            field=models.CharField(blank=True, max_length=3, verbose_name='馬体重'),
        ),
        migrations.AlterField(
            model_name='tyokuzen',
            name='kinryou',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='斤量'),
        ),
    ]
