# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-09 05:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0007_auto_20170909_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyokuzen',
            name='taijyu_zougen',
            field=models.CharField(blank=True, max_length=3, verbose_name='体重増減'),
        ),
    ]
